[tool.poetry]
name = "pathfinder"
version = "0.1.0"
description = "Pathfinding tool"
authors = ["Henrik Laun <dev@web-hl.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pygame = "^2.5.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
